---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: deal-api
spec:
  replicas: {{ int .Values.replicas }}
  selector:
    matchLabels:
      app: deal-api
  template:
    metadata:
      labels:
        app: deal-api
    spec:
      containers:
      - name: api
        image: {{ .Values.image }}
        imagePullPolicy: Always
        command:
        - python
        - -m
        - flask
        - run
        - --host=0.0.0.0
        - --port=5000
        ports:
          - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  selector:
    app: deal-api
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: http
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-production
  labels:
    app: deal-api
  name: {{ .Release.Name }}-ingress
spec:
  tls:
  - hosts:
    - {{ .Values.externalHostname }}
    secretName: {{ .Values.tlsSecret }}
  rules:
  - host: "{{ .Values.externalHostname }}"
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}-service
          servicePort: 80
